services:
  housekeeping-service:
    build: .
    ports:
      - "8082:8082"
    environment:
      DB_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/housekeeping_db
      REDIS_URL: redis://redis:6379/0
      KAFKA_BOOTSTRAP: kafka:9092
      ENVIRONMENT: dev
      JWT_PUBLIC_KEY: "${JWT_PUBLIC_KEY}"
    depends_on:
      - postgres
      - redis
      - kafka

  seeder:
    build: .
    command: python seed.py
    environment:
      DB_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/housekeeping_db
    depends_on:
      postgres:
        condition: service_healthy
    profiles: ["tools"]

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: housekeeping_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      CLUSTER_ID: HkU3OEVBNTcwNTJENDM2Qk
    ports:
      - "9093:9092"

volumes:
  postgres_data:
