"""Custom OpenAPI configuration for FastAPI app."""

from fastapi import FastAPI

def custom_openapi(app: FastAPI):
    """Inject JWT Bearer auth scheme into OpenAPI schema."""
    if app.openapi_schema:
        return app.openapi_schema
    openapi_schema = app.openapi()
    # Add security scheme if not present
    components = openapi_schema.get("components", {})
    security_schemes = components.get("securitySchemes", {})

    # Use "OAuth2PasswordBearer" to match the default name generated by the dependency in app/dependencies.py
    security_schemes["OAuth2PasswordBearer"] = {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
    }
    components["securitySchemes"] = security_schemes
    openapi_schema["components"] = components

    app.openapi_schema = openapi_schema
    return app.openapi_schema
