'''Pydantic schemas for the tasks domain.

These schemas are used by the FastAPI endpoints to validate request bodies
and shape responses. They mirror the fields defined in ``app.domain.tasks.model``
but expose only the data that is relevant to API consumers.
'''

from __future__ import annotations

from datetime import datetime
from typing import Optional, List, Any

from pydantic import BaseModel, Field, ConfigDict

from app.shared.enums import TaskStatus, TaskType


class TaskCreateRequest(BaseModel):
    """Payload for creating a new housekeeping task.

    ``id`` is generated by the database, so it is omitted here.
    """

    room_id: str = Field(..., description="Identifier shared with the reservation service")
    room_number: str = Field(..., description="Human‑readable room number")
    booking_ref: Optional[str] = Field(None, description="Optional booking reference")
    task_type: TaskType = Field(..., description="Type of housekeeping task")
    assigned_staff: Optional[str] = Field(None, description="User ID of the staff member")
    status: TaskStatus = Field(TaskStatus.PENDING, description="Initial status of the task")
    priority: Optional[str] = Field("NORMAL", description="Priority label")
    scheduled_for: Optional[datetime] = Field(None, description="When the task is scheduled")
    cleaning_notes: Optional[str] = Field(None, description="Notes about cleaning")
    damaged_item_notes: Optional[str] = Field(None, description="Notes about damaged items")
    missing_item_notes: Optional[str] = Field(None, description="Notes about missing items")
    supplies_replaced: Optional[List[dict]] = Field(
        None, description="List of supplies used, e.g. [{\"item_id\":..., \"qty\":...}]"
    )
    linked_complaint_id: Optional[str] = Field(None, description="Complaint identifier, if any")


class TaskUpdateRequest(BaseModel):
    """Payload for partial updates to a task.

    All fields are optional – FastAPI will pass only the supplied ones to the
    repository ``update_task`` helper.
    """

    assigned_staff: Optional[str] = None
    status: Optional[TaskStatus] = None
    priority: Optional[str] = None
    scheduled_for: Optional[datetime] = None
    cleaning_notes: Optional[str] = None
    damaged_item_notes: Optional[str] = None
    missing_item_notes: Optional[str] = None
    supplies_replaced: Optional[List[dict]] = None
    linked_complaint_id: Optional[str] = None


class TaskResponse(BaseModel):
    """Full representation of a task as returned by GET endpoints."""

    id: str
    room_id: str
    room_number: str
    booking_ref: Optional[str]
    task_type: TaskType
    assigned_staff: Optional[str]
    status: TaskStatus
    priority: str
    scheduled_for: Optional[datetime]
    started_at: Optional[datetime]
    completed_at: Optional[datetime]
    cleaning_notes: Optional[str]
    damaged_item_notes: Optional[str]
    missing_item_notes: Optional[str]
    supplies_replaced: Optional[List[dict]]
    linked_complaint_id: Optional[str]
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)
